#!/bin/sh
# Generated by render-installer.py. All embedded files come from the release.
set -eu
PATH="/usr/sbin:/usr/bin:/sbin:/bin:/system/sbin:/system/bin${PATH:+:$PATH}"
export PATH
VERSION='0.10.52'
EXPECTED_SHA='683289cc1d69e1964c0c0a04a196ee5440d12dcdffab98d98e99923196152862'
DOWNLOAD_URL=${DATAD_DOWNLOAD_URL:-'https://pan.ericsfj.com/d/github%20releases/zwrt-datad/zwrt-datad-aarch64?sign=ZclbVT-Ki4a-_Fr6FG57o0JE15dxKYdheBOae8yWr_g=:0'}
STANDARD_DIR=/data/zwrt-datad
DIR=${DATAD_INSTALL_DIR:-}
BIN=
CUSTOM=0
RC=/etc/rc.local
WORK=
BACKUP=
SMOKE_PID=
CHANGED=0
STOPPED=0
SUCCESS=0
WAS_RUNNING=0
WAS_CLOUD_RUNNING=0
RC_WRITTEN=0

say() { printf '[datad-install] %s\n' "$*"; }
fail() { say "$*" >&2; exit 1; }
health() { curl -fsS --connect-timeout 2 --max-time 3 "http://127.0.0.1:$1/healthz" >/dev/null; }
wait_health() {
    count=0
    while [ "$count" -lt 20 ]; do
        health "$1" && return 0
        sleep 1; count=$((count+1))
    done
    return 1
}
known_binary() {
    [ -z "$DIR" ] || [ "$1" != "$DIR/zwrt-datad" ] || return 0
    case "$1" in
        /data/zwrt-datad/zwrt-datad|/data/plugins/zwrt-datad/zwrt-datad|/data/data/zwrt-datad/zwrt-datad|/data/plugins/u60-datad/u60-datad|/data/u60-datad/u60-datad) return 0 ;;
        *) return 1 ;;
    esac
}
running_pids() {
    for proc in /proc/[0-9]*; do
        actual=$(readlink "$proc/exe" 2>/dev/null || true)
        actual=${actual% (deleted)}
        if known_binary "$actual"; then printf '%s\n' "${proc##*/}"; fi
    done
}
stop_known() {
    for pid in $(running_pids); do
        kill -TERM "$pid" 2>/dev/null || true
    done
    count=0
    while [ -n "$(running_pids)" ] && [ "$count" -lt 10 ]; do sleep 1; count=$((count+1)); done
    for pid in $(running_pids); do kill -KILL "$pid" 2>/dev/null || true; done
}
legacy_cloud_pids() {
    for proc in /proc/[0-9]*; do
        actual=$(readlink "$proc/exe" 2>/dev/null || true)
        actual=${actual% (deleted)}
        case "$actual" in
            /data/zwrt-datad/zwrt-datad-cloud|/data/plugins/zwrt-datad/zwrt-datad-cloud|/data/data/zwrt-datad/zwrt-datad-cloud)
                printf '%s\n' "${proc##*/}" ;;
        esac
    done
}
stop_legacy_cloud() {
    for pid in $(legacy_cloud_pids); do kill -TERM "$pid" 2>/dev/null || true; done
    count=0
    while [ -n "$(legacy_cloud_pids)" ] && [ "$count" -lt 10 ]; do sleep 1; count=$((count+1)); done
    for pid in $(legacy_cloud_pids); do kill -KILL "$pid" 2>/dev/null || true; done
    rm -f "$DIR/cloud.pid" "$DIR/cloud.sock" "$DIR/cloud.lock"
}
save_file() {
    if [ -e "$1" ]; then cp -p "$1" "$BACKUP/$2"; else : > "$BACKUP/$2.absent"; fi
}
restore_file() {
    if [ -e "$BACKUP/$2" ]; then
        cp -p "$BACKUP/$2" "$1.restore.$$" && mv -f "$1.restore.$$" "$1"
    elif [ -e "$BACKUP/$2.absent" ]; then rm -f "$1"; fi
}
stop_smoke() {
    if [ -n "$SMOKE_PID" ]; then
        kill -TERM "$SMOKE_PID" 2>/dev/null || true
        count=0
        while kill -0 "$SMOKE_PID" 2>/dev/null && [ "$count" -lt 10 ]; do sleep 1; count=$((count+1)); done
        kill -KILL "$SMOKE_PID" 2>/dev/null || true
        wait "$SMOKE_PID" 2>/dev/null || true
        SMOKE_PID=
    fi
}
cleanup() {
    status=$?
    trap - EXIT HUP INT TERM
    set +e
    stop_smoke
    if [ "$SUCCESS" != 1 ] && [ "$CHANGED" = 1 ]; then
        say "安装失败，恢复原文件和服务"
        stop_known
        for name in zwrt-datad service.sh version.json OPENSSL-LICENSE.txt zwrt-datad-cloud cloud-service.sh; do restore_file "$DIR/$name" "$name"; done
        [ "$RC_WRITTEN" = 0 ] || restore_file "$RC" rc.local
        for link in "$BACKUP/legacy-links"/*; do
            [ -L "$link" ] || continue
            cp -P "$link" "/etc/rc.d/${link##*/}"
        done
        if [ "$WAS_RUNNING" = 1 ] && [ -f "$BACKUP/original-service" ]; then
            IFS= read -r original_service < "$BACKUP/original-service"
            sh "$original_service" start 9>&- || true
        elif [ "$WAS_CLOUD_RUNNING" = 1 ] && [ -f "$DIR/cloud-service.sh" ]; then
            sh "$DIR/cloud-service.sh" start 9>&- || true
        fi
    elif [ "$SUCCESS" != 1 ] && [ "$STOPPED" = 1 ] && [ "$WAS_RUNNING" = 1 ]; then
        sh "$DIR/service.sh" start 9>&- || true
    fi
    [ -z "$WORK" ] || rm -rf "$WORK"
    exit "$status"
}

# Install where the running datad lives (explicit DATAD_INSTALL_DIR from the OTA
# wrapper, else the one running datad whose directory has service.sh), so a
# non-standard location is updated in place. The default stays /data/zwrt-datad.
if [ -z "$DIR" ]; then
    found=
    count=0
    for proc in /proc/[0-9]*; do
        actual=$(readlink "$proc/exe" 2>/dev/null || true)
        actual=${actual% (deleted)}
        case "${actual##*/}" in zwrt-datad) ;; *) continue ;; esac
        candidate=${actual%/*}
        case "$candidate" in /tmp/*|"") continue ;; esac
        [ -f "$candidate/service.sh" ] || continue
        [ "$candidate" = "$found" ] || { found=$candidate; count=$((count+1)); }
    done
    if [ "$count" = 1 ]; then DIR=$found; else DIR=$STANDARD_DIR; fi
fi
case "$DIR" in /*) ;; *) fail "安装目录必须是绝对路径：$DIR" ;; esac
case "$DIR" in *[!A-Za-z0-9_./-]*|*..*) fail "安装目录含不允许的字符：$DIR" ;; esac
BIN=$DIR/zwrt-datad
if [ "$(readlink -f "$DIR" 2>/dev/null || printf '%s' "$DIR")" != "$(readlink -f "$STANDARD_DIR" 2>/dev/null || printf '%s' "$STANDARD_DIR")" ]; then CUSTOM=1; fi
[ "$CUSTOM" = 0 ] || say "沿用已安装目录：$DIR（不改写 rc.local）"

[ "$(id -u)" = 0 ] || fail "请使用 root 执行"
case "$(uname -m)" in aarch64|arm64) ;; *) fail "仅支持 ARM64/aarch64" ;; esac
for cmd in curl sha256sum awk cmp stat flock mktemp readlink od; do
    command -v "$cmd" >/dev/null 2>&1 || fail "缺少命令：$cmd"
done
case "$DOWNLOAD_URL" in https://*) ;; *) fail "下载地址必须为 HTTPS" ;; esac
mkdir -p "$DIR"
exec 9> "$DIR/.install.lock"
flock -n 9 || fail "另一个安装进程正在运行"
umask 077
WORK=$(mktemp -d /tmp/datad-install.XXXXXX)
trap cleanup EXIT
trap 'exit 130' HUP INT TERM

cat > "$WORK/service.sh" <<'DATAD_SERVICE_EOF'
#!/system/bin/sh

# Default to the directory this script lives in, so an install kept outside
# /data/zwrt-datad keeps working; fall back to the standard path.
SERVICE_DIR="${ZWRT_DATAD_DIR:-$(cd "$(dirname "$0")" 2>/dev/null && pwd)}"
SERVICE_DIR="${SERVICE_DIR:-/data/zwrt-datad}"
export ZWRT_DATAD_DIR="$SERVICE_DIR"
BIN="${ZWRT_DATAD_BIN:-$SERVICE_DIR/zwrt-datad}"
PID_FILE="${ZWRT_DATAD_PID_FILE:-$SERVICE_DIR/zwrt-datad.pid}"
LOG_FILE="${ZWRT_DATAD_LOG_FILE:-$SERVICE_DIR/zwrt-datad.log}"
TOKEN_FILE="${ZWRT_DATAD_TOKEN_FILE:-$SERVICE_DIR/auth.token}"

binary_real_path() {
    path="$(readlink -f "$BIN" 2>/dev/null)"
    [ -n "$path" ] && printf '%s\n' "$path" || printf '%s\n' "$BIN"
}

process_matches() {
    check_pid="$1"
    case "$check_pid" in
        ''|*[!0-9]*) return 1 ;;
    esac
    [ -d "/proc/$check_pid" ] || return 1

    expected="$(binary_real_path)"
    actual="$(readlink "/proc/$check_pid/exe" 2>/dev/null)"
    actual="${actual% (deleted)}"
    if [ -n "$actual" ] && { [ "$actual" = "$expected" ] || [ "$actual" = "$BIN" ]; }; then
        return 0
    fi
    first_arg="$(tr '\000' '\n' 2>/dev/null < "/proc/$check_pid/cmdline" | sed -n '1p')"
    [ "$first_arg" = "$expected" ] || [ "$first_arg" = "$BIN" ]
}

write_pid() {
    tmp_pid_file="$PID_FILE.$$"
    umask 022
    printf '%s\n' "$1" > "$tmp_pid_file" && mv -f "$tmp_pid_file" "$PID_FILE"
}

find_running_pid() {
    for proc_dir in /proc/[0-9]*; do
        scan_pid="${proc_dir#/proc/}"
        if process_matches "$scan_pid"; then
            printf '%s\n' "$scan_pid"
            return 0
        fi
    done
    return 1
}

running_pid() {
    if [ -f "$PID_FILE" ]; then
        IFS= read -r saved_pid < "$PID_FILE"
        if process_matches "$saved_pid"; then
            printf '%s\n' "$saved_pid"
            return 0
        fi
        rm -f "$PID_FILE"
    fi
    found_pid="$(find_running_pid)"
    if [ -n "$found_pid" ]; then
        write_pid "$found_pid" >/dev/null 2>&1 || true
        printf '%s\n' "$found_pid"
        return 0
    fi
    return 1
}

stop_legacy_cloud() {
    [ ! -f "$SERVICE_DIR/cloud-service.sh" ] || sh "$SERVICE_DIR/cloud-service.sh" stop >/dev/null 2>&1 || true
    rm -f "$SERVICE_DIR/cloud.pid" "$SERVICE_DIR/cloud.sock" "$SERVICE_DIR/cloud.lock"
}

ensure_auth_token() {
    if [ -e "$TOKEN_FILE" ] || [ -L "$TOKEN_FILE" ]; then
        if [ ! -f "$TOKEN_FILE" ] || [ -L "$TOKEN_FILE" ] || [ ! -s "$TOKEN_FILE" ]; then
            echo "zwrt-datad 启动失败：$TOKEN_FILE 必须是非空普通文件" >&2
            return 1
        fi
        chmod 600 "$TOKEN_FILE" 2>/dev/null || return 1
        return 0
    fi

    token_dir="${TOKEN_FILE%/*}"
    [ "$token_dir" != "$TOKEN_FILE" ] || token_dir=.
    mkdir -p "$token_dir" || return 1
    token_tmp="$TOKEN_FILE.new.$$"
    umask 077
    (set -C; : > "$token_tmp") 2>/dev/null || {
        echo "zwrt-datad 启动失败：无法安全创建 Token 临时文件" >&2
        return 1
    }
    generated_token="$(od -An -N32 -tx1 /dev/urandom | tr -d ' \n')"
    case "$generated_token" in
        *[!0-9a-f]*|'') rm -f "$token_tmp"; return 1 ;;
    esac
    if [ "${#generated_token}" -ne 64 ] ||
        ! printf '%s\n' "$generated_token" > "$token_tmp"; then
        rm -f "$token_tmp"
        return 1
    fi
    chmod 600 "$token_tmp" && mv -f "$token_tmp" "$TOKEN_FILE"
}

discover_cooling_paths() {
    if [ -z "${ZWRT_DATAD_COOLING_ZONE_PATH:-}" ]; then
        for type_file in /sys/class/thermal/thermal_zone*/type; do
            [ -f "$type_file" ] || continue
            [ "$(cat "$type_file" 2>/dev/null)" = "sys-therm-4" ] || continue
            ZWRT_DATAD_COOLING_ZONE_PATH="${type_file%/type}"
            export ZWRT_DATAD_COOLING_ZONE_PATH
            break
        done
    fi
    if [ -z "${ZWRT_DATAD_FAN_COOLING_STATE_PATH:-}" ]; then
        for type_file in /sys/class/thermal/cooling_device*/type; do
            [ -f "$type_file" ] || continue
            [ "$(cat "$type_file" 2>/dev/null)" = "pwm-fan" ] || continue
            ZWRT_DATAD_FAN_COOLING_STATE_PATH="${type_file%/type}/cur_state"
            export ZWRT_DATAD_FAN_COOLING_STATE_PATH
            break
        done
    fi
}

start() {
    active_pid="$(running_pid)"
    if [ -n "$active_pid" ]; then
        stop_legacy_cloud
        echo "zwrt-datad 正在运行 (PID $active_pid)"
        return 0
    fi
    if [ ! -f "$BIN" ]; then
        echo "zwrt-datad 启动失败：找不到 $BIN" >&2
        return 1
    fi
    chmod 755 "$BIN" 2>/dev/null || true
    if [ ! -x "$BIN" ]; then
        echo "zwrt-datad 启动失败：$BIN 不可执行" >&2
        return 1
    fi

    mkdir -p "$SERVICE_DIR" || return 1
    cd "$SERVICE_DIR" || return 1
    stop_legacy_cloud
    ensure_auth_token || return 1
    discover_cooling_paths
    nohup "$BIN" -i 1000 -b 127.0.0.1 -p 9460 --webshell \
        --lan-bind 0.0.0.0 --lan-port 9461 --auth-token-file "$TOKEN_FILE" \
        >> "$LOG_FILE" 2>&1 </dev/null &
    launched_pid=$!
    sleep 1
    if process_matches "$launched_pid"; then
        write_pid "$launched_pid" || true
        stop_legacy_cloud
        echo "zwrt-datad 已启动 (PID $launched_pid)"
        return 0
    fi
    active_pid="$(find_running_pid)"
    if [ -n "$active_pid" ]; then
        write_pid "$active_pid" || true
        stop_legacy_cloud
        echo "zwrt-datad 已启动 (PID $active_pid)"
        return 0
    fi
    rm -f "$PID_FILE"
    echo "zwrt-datad 启动失败，请检查 $LOG_FILE" >&2
    return 1
}

stop() {
    stop_legacy_cloud
    active_pid="$(running_pid)"
    if [ -z "$active_pid" ]; then
        rm -f "$PID_FILE"
        echo "zwrt-datad 未在运行"
        return 0
    fi
    kill -TERM "$active_pid" 2>/dev/null || true
    wait_count=0
    while process_matches "$active_pid" && [ "$wait_count" -lt 10 ]; do
        sleep 1
        wait_count=$((wait_count + 1))
    done
    if process_matches "$active_pid"; then
        kill -KILL "$active_pid" 2>/dev/null || true
    fi
    rm -f "$PID_FILE"
    echo "zwrt-datad 已停止"
}

status() {
    active_pid="$(running_pid)"
    if [ -n "$active_pid" ]; then
        echo "zwrt-datad 正在运行 (PID $active_pid)"
        return 0
    fi
    echo "zwrt-datad 未在运行"
    return 1
}

case "$1" in
    start) start ;;
    stop) stop ;;
    restart) stop && start ;;
    status) status ;;
    *)
        echo "用法: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac
DATAD_SERVICE_EOF
cat > "$WORK/version.json" <<'DATAD_MANIFEST_EOF'
{
  "schema": 1,
  "datad": {
    "version": "0.10.52",
    "asset": "zwrt-datad-aarch64",
    "notes": "MU5252 外挂基带接口改用原厂名称：5G / 4G1（V3E2）/ 4G2（V3E1）；短信 sender 同步，旧编号仍可用"
  }
}
DATAD_MANIFEST_EOF
cat > "$WORK/rc.awk" <<'DATAD_RC_AWK_EOF'
# Render only datad startup entries; preserve all unrelated commands.
function trim(s) { sub(/^[ \t]+/, "", s); sub(/[ \t\r]+$/, "", s); return s }
function datad_path(s) {
    return s ~ /^\/(data\/(plugins\/|data\/)?(zwrt-datad|u60-datad)\/(service\.sh|cloud-service\.sh|zwrt-datad|u60-datad)|etc\/init\.d\/(zwrt-datad|u60-datad))$/
}
function plain(s,    a,n,i,p,check) {
    s=trim(s)
    sub(/[ \t]+#.*/, "", s)
    gsub(/["\047]/, "", s)
    n=split(s,a,/[ \t]+/); i=1
    while (i<=n && (a[i]=="nohup" || a[i]=="sh" || a[i]=="/bin/sh" || a[i]=="/system/bin/sh" || a[i]=="exec")) i++
    p=a[i]
    if (!datad_path(p)) return 0
    if (p ~ /service\.sh$/ || p ~ /^\/etc\/init\.d\//) {
        if (a[i+1]!="start" && a[i+1]!="restart" && a[i+1]!="enable") return 0
    }
    # Never remove a second, unrelated command on the same logical line.
    check=s
    gsub(/[012]?>&[012]/, "", check)
    if (check ~ /[;|]/ || check ~ /&&/ || check ~ /&[ \t]*[^ \t]/) return 0
    return 1
}
function startup(s,    t) {
    if (plain(s)) return 1
    t=trim(s)
    # Common one-line file/executable guard around a single start command.
    if (t ~ /^(\[|test)[ \t]+-(f|x)[ \t]/ && t ~ /&&/) {
        sub(/^.*&&[ \t]*/, "", t)
        return plain(t)
    }
    return 0
}
function guarded(s,    t,a,n) {
    t=trim(s); gsub(/["\047]/,"",t)
    if (t !~ /^if[ \t]+\[[ \t]+-(f|x)[ \t]+.*[ \t]+\][ \t]*;[ \t]*then$/) return 0
    n=split(t,a,/[ \t]+/)
    return datad_path(a[4])
}
function flush_line(raw,logical,    t) {
    t=trim(logical)
    if (t ~ /^# (BEGIN|END) (zwrt-datad|u60-datad) managed startup$/) return
    if (startup(t)) {
        removed++
        if (!first_removed) first_removed=count+1
        return
    }
    if (t !~ /^#/ && t ~ /\/(zwrt-datad|u60-datad)(\/(cloud-)?service\.sh|[ \t"\047]|$)/) {
        print "Unsupported mixed datad startup command; rc.local left unchanged" > "/dev/stderr"
        bad=1
    }
    count++; lines[count]=raw
    if (t ~ /^(fi|done|esac)([ \t;]|$)/ && depth>0) depth--
    if (!boundary && depth==0 && t ~ /^exit([ \t]|$)/) boundary=count
    if (!boundary && (t ~ /\/ufi-tools\/service\.sh[ \t]+start/ || t ~ /\/ufitools[^ \t]*\/service\.sh[ \t]+start/)) boundary=depth>0 ? outer_start : count
    if (t ~ /^(if|for|while|until|case)[ \t]/ && t !~ /;[ \t]*(fi|done|esac)([ \t;]|$)/) {
        if (depth==0) outer_start=count
        depth++
    }
}
{
    if (raw!="") raw=raw "\n"
    raw=raw $0
    part=$0
    if (part ~ /\\[ \t]*$/) {
        sub(/\\[ \t]*$/, "", part); logical=logical part " "; next
    }
    logical=logical part
    record_count++; record_raw[record_count]=raw; record_text[record_count]=logical
    raw=""; logical=""
}
END {
    if (raw!="") { print "Incomplete shell continuation" > "/dev/stderr"; bad=1 }
    for (record=1;record<=record_count;record++) {
        if (guarded(record_text[record]) && startup(record_text[record+1]) && trim(record_text[record+2])=="fi") {
            flush_line(record_raw[record+1],record_text[record+1]); record+=2
        } else flush_line(record_raw[record],record_text[record])
    }
    if (bad) exit 2
    insert=boundary ? boundary : count+1
    if (first_removed && first_removed<insert) insert=first_removed
    for (i=1;i<=count+1;i++) {
        if (i==insert) print "sh /data/zwrt-datad/service.sh start"
        if (i<=count) print lines[i]
    }
}
DATAD_RC_AWK_EOF

# Validate boot changes before touching the running service. A datad kept in a
# non-standard directory keeps the operator's own boot entry untouched.
if [ "$CUSTOM" = 1 ]; then
    : > "$WORK/rc.before"
    : > "$WORK/rc.after"
elif [ -e "$RC" ]; then
    [ -f "$RC" ] && [ ! -L "$RC" ] || fail "rc.local 必须是普通文件"
    cp -p "$RC" "$WORK/rc.before"
else
    printf '#!/bin/sh\n\nexit 0\n' > "$WORK/rc.before"
fi
awk -f "$WORK/rc.awk" "$WORK/rc.before" > "$WORK/rc.after" || fail "无法安全整理 rc.local"
sh -n "$WORK/rc.after" || fail "整理后的 rc.local 语法错误"
RC_CHANGED=1
if [ "$CUSTOM" = 1 ] || { [ -f "$RC" ] && cmp -s "$RC" "$WORK/rc.after"; }; then RC_CHANGED=0; fi

# An enabled legacy init script would start a duplicate before rc.local.
# Keep the script itself; remove only its boot symlinks after success.
: > "$WORK/legacy-links"
for link in /etc/rc.d/*; do
    [ "$CUSTOM" = 0 ] || break
    [ -L "$link" ] || continue
    target=$(readlink -f "$link" 2>/dev/null || true)
    case "$target" in
        /etc/init.d/zwrt-datad|/etc/init.d/u60-datad) printf '%s\n' "$link" >> "$WORK/legacy-links" ;;
    esac
done

if [ -f "$BIN" ] && [ "$(sha256sum "$BIN" | awk '{print $1}')" = "$EXPECTED_SHA" ]; then
    cp "$BIN" "$WORK/zwrt-datad"
    say "现有二进制校验一致，跳过重复下载"
else
    say "下载 datad v$VERSION"
    attempt=1
    while ! curl -4fLsS --connect-timeout 15 --max-time 180 "$DOWNLOAD_URL" -o "$WORK/zwrt-datad"; do
        rm -f "$WORK/zwrt-datad"
        [ "$attempt" -lt 3 ] || fail "下载失败，原安装保持不变"
        attempt=$((attempt+1)); say "下载中断，重试 $attempt/3"; sleep 2
    done
fi
printf '%s  %s\n' "$EXPECTED_SHA" "$WORK/zwrt-datad" | sha256sum -c - >/dev/null || fail "二进制 SHA-256 不匹配"
[ "$(od -An -tx1 -N6 "$WORK/zwrt-datad" | tr -d ' \n')" = 7f454c460201 ] || fail "不是 ELF64 little-endian 二进制"
[ "$(od -An -tx1 -j18 -N2 "$WORK/zwrt-datad" | tr -d ' \n')" = b700 ] || fail "二进制不是 AArch64"
chmod 755 "$WORK/zwrt-datad"
"$WORK/zwrt-datad" --help >/dev/null || fail "临时二进制启动检查失败"

FILES_CHANGED=0
BINARY_CHANGED=0
SERVICE_CHANGED=0
for name in zwrt-datad service.sh version.json; do
    if ! cmp -s "$WORK/$name" "$DIR/$name"; then
        FILES_CHANGED=1
        [ "$name" != zwrt-datad ] || BINARY_CHANGED=1
        [ "$name" != service.sh ] || SERVICE_CHANGED=1
    fi
done
[ -x "$BIN" ] || BINARY_CHANGED=1
PIDS=$(running_pids)
[ -z "$PIDS" ] || WAS_RUNNING=1
CLOUD_PIDS=$(legacy_cloud_pids)
[ -z "$CLOUD_PIDS" ] || WAS_CLOUD_RUNNING=1
LEGACY_RESIDUE=0
[ -z "$CLOUD_PIDS" ] || LEGACY_RESIDUE=1
for legacy_cloud_file in zwrt-datad-cloud cloud-service.sh cloud.pid cloud.sock cloud.lock; do
    [ ! -e "$DIR/$legacy_cloud_file" ] || LEGACY_RESIDUE=1
done
[ ! -e "$DIR/OPENSSL-LICENSE.txt" ] || LEGACY_RESIDUE=1
NEED_START=1
if [ "$BINARY_CHANGED" = 0 ] && [ "$SERVICE_CHANGED" = 0 ] && [ "$(printf '%s\n' "$PIDS" | awk 'NF{n++} END{print n+0}')" = 1 ] && health 9460 && health 9461; then
    actual=$(readlink "/proc/$PIDS/exe" 2>/dev/null || true)
    [ "$actual" != "$BIN" ] || NEED_START=0
fi
if [ "$FILES_CHANGED" = 0 ] && [ "$RC_CHANGED" = 0 ] && [ ! -s "$WORK/legacy-links" ] && [ "$NEED_START" = 0 ] && [ "$LEGACY_RESIDUE" = 0 ]; then
    SUCCESS=1
    say "v$VERSION 已安装；安装文件和自启一致，无需重写或重启服务"
    exit 0
fi

# The new binary is copied beside the old one and the old one is backed up
# while installing: require room for both on the filesystem holding $DIR.
need_kb=$(( $(stat -c %s "$WORK/zwrt-datad") / 1024 * 3 + 1024 ))
have_kb=$(df -Pk "$DIR" 2>/dev/null | awk 'NR==2{print $4}')
case "$have_kb" in ''|*[!0-9]*) ;; *) [ "$have_kb" -ge "$need_kb" ] || fail "$DIR 所在分区可用空间不足：需要约 ${need_kb} KiB，仅有 ${have_kb} KiB" ;; esac
BACKUP="$DIR/backups/install-$(date +%Y%m%d-%H%M%S)-$$"
mkdir -p "$BACKUP"
chmod 700 "$BACKUP"
for name in zwrt-datad service.sh version.json OPENSSL-LICENSE.txt zwrt-datad-cloud cloud-service.sh; do save_file "$DIR/$name" "$name"; done
save_file "$RC" rc.local
printf '%s\n' "$DIR/service.sh" > "$BACKUP/original-service"
CHANGED=1
for pid in $PIDS; do
    old=$(readlink "/proc/$pid/exe" 2>/dev/null || true); old=${old% (deleted)}
    old_dir=${old%/*}
    if [ "$old_dir" != "$DIR" ] && [ -f "$old_dir/service.sh" ]; then
        printf '%s\n' "$old_dir/service.sh" > "$BACKUP/original-service"
        # Preserve existing device configuration when migrating a known path.
        for config in auth.token cloud.json cooling.conf; do
            if [ ! -e "$DIR/$config" ] && [ -f "$old_dir/$config" ]; then cp -p "$old_dir/$config" "$DIR/$config"; fi
        done
    fi
done
if [ "$LEGACY_RESIDUE" = 1 ]; then stop_legacy_cloud; fi
if [ "$NEED_START" = 1 ]; then
    IFS= read -r original_service < "$BACKUP/original-service"
    if [ -f "$original_service" ]; then sh "$original_service" stop 9>&-; fi
    for legacy_init in /etc/init.d/zwrt-datad /etc/init.d/u60-datad; do
        [ ! -f "$legacy_init" ] || sh "$legacy_init" stop 9>&-
    done
    stop_known
    STOPPED=1
    # Only one datad controller runs at a time, including this loopback smoke.
    (cd "$DIR" && ZWRT_DATAD_DIR="$WORK/cloud" exec "$WORK/zwrt-datad" -b 127.0.0.1 -p 19460 -i 1000) > "$WORK/smoke.log" 2>&1 9>&- &
    SMOKE_PID=$!
    wait_health 19460 || fail "临时服务健康检查失败"
    [ "$(readlink "/proc/$SMOKE_PID/exe" 2>/dev/null || true)" = "$WORK/zwrt-datad" ] || fail "临时端口未由候选进程提供"
    curl -fsS --max-time 10 http://127.0.0.1:19460/state -o /dev/null || fail "临时状态接口检查失败"
    stop_smoke
fi

for name in zwrt-datad service.sh version.json; do
    if ! cmp -s "$WORK/$name" "$DIR/$name"; then
        cp "$WORK/$name" "$DIR/$name.new.$$"
        case "$name" in zwrt-datad|service.sh) chmod 755 "$DIR/$name.new.$$" ;; *) chmod 644 "$DIR/$name.new.$$" ;; esac
        mv -f "$DIR/$name.new.$$" "$DIR/$name"
    fi
done
if [ "$NEED_START" = 1 ]; then sh "$DIR/service.sh" start 9>&-; fi
wait_health 9460 && wait_health 9461 || fail "正式服务健康检查失败"
curl -fsS --max-time 10 http://127.0.0.1:9460/state -o /dev/null || fail "正式状态接口检查失败"
[ "$(running_pids | awk 'NF{n++} END{print n+0}')" = 1 ] || fail "检测到重复 datad 进程"

if [ "$RC_CHANGED" = 1 ]; then
    # Detect an operator changing rc.local while download/smoke was running.
    if [ -e "$RC" ]; then cmp -s "$RC" "$WORK/rc.before" || fail "安装期间 rc.local 被其他程序修改"; fi
    cp "$WORK/rc.after" "$RC.new.$$"
    if [ -e "$RC" ]; then
        chmod "$(stat -c %a "$RC")" "$RC.new.$$"
        chown "$(stat -c %u "$RC"):$(stat -c %g "$RC")" "$RC.new.$$"
    else chmod 755 "$RC.new.$$"; fi
    chmod u+x "$RC.new.$$"
    mv -f "$RC.new.$$" "$RC"
    RC_WRITTEN=1
    say "已清理旧自启项，写入唯一标准启动命令"
else say "自启项一致，rc.local 未重写"; fi
mkdir -p "$BACKUP/legacy-links"
while IFS= read -r link; do
    [ -n "$link" ] || continue
    cp -P "$link" "$BACKUP/legacy-links/${link##*/}"
    rm "$link"
done < "$WORK/legacy-links"
rm -f "$DIR/zwrt-datad-cloud" "$DIR/cloud-service.sh" "$DIR/cloud.pid" "$DIR/cloud.sock" "$DIR/cloud.lock" "$DIR/OPENSSL-LICENSE.txt"
SUCCESS=1
rm -rf "$BACKUP"
[ ! -e "$BACKUP" ] || fail "安装成功，但临时回滚备份清理失败：$BACKUP"
BACKUP=
say "安装完成：v$VERSION，$BIN"
say "自启：sh $DIR/service.sh start"
say "临时回滚备份已删除"
